name: 'Horusec - Bom Dia Codigo'
description: 'Horusec SAST Github Action for Bom Dia Codigo labs'
inputs:
  path:
    description: Target directory passed to Horusec via -p
    required: false
    default: ./
  arguments:
    description: Additional arguments forwarded to horusec start
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install Horusec CLI
      shell: bash
      run: |
        set -euo pipefail
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
    - name: Run Horusec
      shell: bash
      env:
        HORUSEC_EXTRA_ARGS: ${{ inputs.arguments }}
      run: |
        set -euo pipefail
        horusec start -p "${{ inputs.path }}" ${HORUSEC_EXTRA_ARGS}
branding:
  icon: 'check'
  color: 'green'
