name: 'Horusec - Bom Dia Codigo'
description: 'Horusec SAST Github Action for Bom Dia Codigo labs'
inputs:
  arguments:
    description: Arguments for horusec
    required: false
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}


branding:
  icon: "check"
  color: "green"
